import type { Metadata } from "next"
import { Outfit } from "next/font/google"
import HolyLoader from "holy-loader"

import "./globals.css"

import QueryProvider from "@/context/queryProvider"

import { cn } from "@/lib/utils"
import { Toaster } from "@/components/ui/sonner"

const outfit = Outfit({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={cn(outfit.className)}>
      <body className={"flex min-h-screen flex-col antialiased"}>
        <HolyLoader
          color="hsl(var(--primary))"
          height={3}
          speed={250}
          easing="linear"
          showSpinner={false}
        />
        <Toaster position="top-right" />
        <QueryProvider>
          <main className="flex min-h-screen flex-col">{children}</main>
        </QueryProvider>
      </body>
    </html>
  )
}
