import type { Metadata } from "next"
import { GeistMono } from "geist/font/mono"
import { GeistSans } from "geist/font/sans"
import HolyLoader from "holy-loader"

import "./globals.css"

import QueryProvider from "@/context/queryProvider"

import { cn } from "@/lib/utils"
import { Toaster } from "@/components/ui/sonner"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={cn(GeistSans.variable, GeistMono.variable)}>
      <body className={"flex min-h-screen flex-col antialiased"}>
        {/* <AuthWrapper> */} {/* Wrapping the entire app with AuthWrapper */}
        {/* <GlobalProvider> */}
        <HolyLoader
          color="hsl(var(--primary))"
          height={3}
          speed={250}
          easing="linear"
          showSpinner={false}
        />
        <Toaster position="top-right" />
        <QueryProvider>{children}</QueryProvider>
        {/* </GlobalProvider> */}
        {/* </AuthWrapper> */}
      </body>
    </html>
  )
}
