# fly.toml app configuration file generated for mangohr on 2024-06-23T20:22:04+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mangohr'
primary_region = 'iad'

[build]
[build.args]
PROJECT = "www"

[http_service]
internal_port = 3000
force_https = true
auto_start_machines = true
auto_stop_machines = "stop"
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
