name: Deploy to App Runner
on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref }}-mangohr-ca
  cancel-in-progress: true

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ROLE_TO_ASSUME: ${{ vars.AWS_ROLE_TO_ASSUME }}
  AWS_REGION: ${{ vars.ECR_REPO }}
  ROLE_ARN: ${{ vars.ROLE_ARN }}
  APP_RUNNER_SERVICE_NAME: ${{ vars.APP_RUNNER_SERVICE_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    permissions:
        contents: 'read'
        id-token: 'write'
            
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # Use GitHub OIDC provider
          role-to-assume: ${{ env.AWS_ASSUME_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPO }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Deploy to App Runner
        id: deploy-apprunner
        uses: awslabs/amazon-app-runner-deploy@main
        env:
          SECRET_ENV: secret_env
        with:
          service: ${{ env.APP_RUNNER_SERVICE_NAME }}
          image: ${{ steps.build-image.outputs.image }}
          access-role-arn: ${{ env.ROLE_ARN }}
          region: ${{ env.AWS_REGION }}
          cpu: 0.25
          memory: 0.5
          wait-for-service-stability-seconds: 600
          copy-secret-env-vars: |
            SECRET_ENV

      - name: App Runner URL
        run: echo "App runner URL ${{ steps.deploy-apprunner.outputs.service-url }}"
