# name: Trigger Fork Sync

# on:
#   push:
#     branches:
#       - main # Adjust based on your default branch

# jobs:
#   notify-fork:
#     if: github.repository == ${{ secrets.DEPLOY_REPO }}
#     runs-on: ubuntu-latest
#     steps:
#       - name: Send webhook to fork
#         run: |
#           curl -X POST -H "Authorization: token ${{ secrets.DEPLOY_REPO_PAT }}" \
#                -H "Accept: application/vnd.github.everest-preview+json" \
#                https://api.github.com/repos/${{ secrets.DEPLOY_REPO }}/dispatches \
#                -d '{"event_type": "sync"}'
